version: '3.9'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./Server:/var/www/html
      - ./Client:/var/www/Client
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - default
  webapp:
    build: ./docker/php
    image: myapp:symfony
    volumes:
      - ./Server:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - default
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a1b2c3
      MYSQL_DATABASE: myapp
    ports:
      - '33061:3306'
    volumes:
      - mysql-datavolume3:/var/lib/mysql
    networks:
      - default
  node:
    build: ./docker/node
    image: myapp:node
    volumes:
      - ./Client:/app
    ports:
      - '4200:4200'
    networks:
      - default
  mercure:
    image: dunglas/mercure
    environment:
      - MERCURE_PUBLISHER_JWT_KEY=!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+Kb
      - MERCURE_SUBSCRIBER_JWT_KEY=dSgVkYp3s6v8y/B?E(H+MbQeThWmZq4t
      - DEMO=1
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
      - DEBUG=1
      - MERCURE_EXTRA_DIRECTIVES=heartbeat 15s
      - SERVER_NAME=:80
    ports:
      - target: 80
        published: 9090
        protocol: tcp
    networks:
      - default
volumes:
  mysql-datavolume3:
